spring:
  redis:
    host: 192.168.1.108
    port: '6379'
    database: '4'
    password: nxzdk@2020
    timeout: 10000
  datasource:
    name: eiot
    url: jdbc:sqlite::resource:wvp.sqlite
    username: null
    password: null
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.sqlite.JDBC
    max-active: 1
    min-idle: 1
server:
  port: '18084'
  ssl:
    enabled: false
    key-store: classpath:xxx.jks
    key-password: password
    key-store-type: JKS
sip:
  ip: 192.168.1.44
  port: '5060'
  domain: '4401020049'
  id: '44010200492000000001'
  password: admin123
media:
  ip: 192.168.1.132
  wanIp: null
  hookIp: null
  httpPort: '80'
  httpSSlPort: null
  rtmpPort: null
  rtmpSSlPort: null
  rtpProxyPort: null
  rtspPort: null
  rtspSSLPort: null
  autoConfig: true
  secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
  streamNoneReaderDelayMS: '18000'
  rtp:
    enable: true
    portRange: 30000,30500
  autoconfig: 'true'
logging:
  file:
    name: logs/wvp.log
    max-history: 30
    max-size: 10MB
    total-size-cap: 300MB
  level:
    com:
      genersoft:
        iot: info
userSettings:
  autoApplyPlay: false
  seniorSdp: false
  savePositionHistory: false
  playTimeout: 3000
  waitTrack: false
  interfaceAuthentication: true
springfox:
  documentation:
    swagger-ui:
      enabled: true
